site_name: "pyDVL"
site_dir: "docs_build"
site_url: "https://appliedai-initiative.github.io/pyDVL/"
repo_url: "https://github.com/appliedAI-Initiative/pyDVL"
copyright: "Copyright &copy; AppliedAI Institute gGmbH"

watch:
  - src/pydvl
  - notebooks

hooks:
  - build_scripts/copy_notebooks.py
  - build_scripts/copy_changelog.py

plugins:
  - mike
  - autorefs
  - search
  - macros
  - section-index
  - alias:
      use_relative_link: true
      verbose: true
  - gen-files:
      scripts:
        - build_scripts/generate_api_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: false
      tab_length: 2
  - mkdocs-jupyter:
      include: ["docs/examples/*.ipynb"]
      remove_tag_config:
        remove_cell_tags:
          - hide
        remove_input_tags:
          - hide-input
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
          paths: [ src ]  # search packages in the src folder
          options:
            docstring_style: google
            docstring_section_style: spacy
            line_length: 80
            show_bases: true
            members_order: source
            show_submodules: false
            show_signature_annotations: false
            signature_crossrefs: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
  - bibtex:
      bib_file: "docs/assets/pydvl.bib"
      csl_file: "docs/assets/elsevier-harvard.csl"
      cite_inline: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
      fallback_to_build_date: true

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/signet.svg
  favicon: assets/signet.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
#    - navigation.indexes
    - navigation.instant
    - navigation.path
#    - navigation.sections
#    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
  palette: # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/extra.css
  - css/neoteroi.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  transferlab:
    website: https://transferlab.appliedai.de
    data_valuation_review: https://transferlab.appliedai.de/reviews/data-valuation
  copyright_link: https://appliedai-institute.de
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/appliedAI-Initiative/pyDVL
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyDVL/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aai_transferlab
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/company/appliedai-institute-for-europe-ggmbh

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - neoteroi.cards
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - First steps: getting-started/getting-started.md
  - Data Valuation:
    - Introduction: value/index.md
    - Shapley Values: value/shapley.md
    - Semi-values: value/semi-values.md
    - The core: value/the-core.md
    - Examples:
      - Shapley values: examples/shapley_basic_spotify.ipynb
      - KNN Shapley: examples/shapley_knn_flowers.ipynb
      - Data utility learning: examples/shapley_utility_learning.ipynb
      - Least Core: examples/least_core_basic.ipynb
  - The Influence Function:
    - Introduction: influence/index.md
    - Examples:
      - For CNNs: examples/influence_imagenet.ipynb
      - For mislabeled data: examples/influence_synthetic.ipynb
      - For outlier detection: examples/influence_wine.ipynb
  - Code:
    - Changelog: CHANGELOG.md
    - API: api/pydvl/
